apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deployment
spec:
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
        - name: identity
          image: play.identity:1.0.15
          env:
            # define path base from api gateway (identity-svc, please check Play.Infra)
            - name: IdentitySettings__PathBase
              value: /identity-svc
            - name: RabbitMqSettings__Host
              # for window open command prompt and run "ipconfig", choose IPV4
              #  value: "172.26.112.1"
              # for mac open wifi and and click details on your name of wifi you are connecting and check IP address
              value: "192.168.1.13"
            - name: MongoDbSettings__Host
              # for window open command prompt and run "ipconfig", choose IPV4
              #  value: "172.26.112.1"
              # for mac open wifi and and click details on your name of wifi you are connecting and check IP address
              value: "192.168.1.13"
            - name: IdentityServerSettings__Clients__1__RedirectUris__0
              value: http://playeconomyapigateway.com/authentication/login-callback
            - name: IdentityServerSettings__Clients__1__PostLogoutRedirectUris__0
              value: http://playeconomyapigateway.com/authentication/logout-callback
            - name: IdentitySettings__AdminUserPassword
              value: Pass@word1

            - name: IdentitySettings__IsKubernetesLocal
              value: "true"

          resources:
            limits:
              memory: "128Mi"
              cpu: "150m"
          ports:
            - containerPort: 5002

          # Kubernetes health probes
          livenessProbe:
            httpGet:
              path: /health/live
              port: 5002
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 5002
            initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  type: ClusterIP
  selector:
    app: identity
  ports:
    - port: 80
      targetPort: 5002
