apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deployment
spec:
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
        - name: identity
          image: play.identity:1.0.9
          env:
            # define path base from api gateway (identity-svc, please check Play.Infra)
            - name: IdentitySettings__PathBase
              value: /identity-svc

            # after configuring TLS certificate, this uses for signing key for authen/author
            - name: IdentitySettings__CertificateCerFilePath
              value: "/certificates/certificate.crt"
            - name: IdentitySettings__CertificateKeyFilePath
              value: "/certificates/certificate.key"

            # this is the Kubernetes secrets, after we created secret from Key Vault, we no need the Kubernetes secrets
            # - name: MongoDbSettings__ConnectionString
            #   # valueFrom where we can use secret values
            #   valueFrom:
            #     secretKeyRef:
            #       # identity-screts is the name of secret you create in Kubernetes, pls check README.
            #       name: identity-secrets
            #       key: cosmosdb-connectionstring
            # - name: ServiceBusSetting__ConnectionString
            #   valueFrom:
            #     secretKeyRef:
            #       name: identity-secrets
            #       key: servicebus-connectionstring
            # - name: IdentitySettings__AdminUserPassword
            #   valueFrom:
            #     secretKeyRef:
            #       name: identity-secrets
            #       key: admin-password

          resources:
            limits:
              memory: "128Mi"
              cpu: "150m"
          ports:
            - containerPort: 5002

          # Kubernetes health probes
          livenessProbe:
            httpGet:
              path: /health/live
              port: 5002
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 5002
            initialDelaySeconds: 10

      #     volumeMounts:
      #       - name: certificate-volume
      #         mountPath: /certificates
      # volumes:
      #   - name: certificate-volume
      #     secret:
      #       secretName: signing-cert
      #       items:
      #         - key: tls.key
      #           path: certificate.key
      #         - key: tls.crt
      #           path: certificate.crt

---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  type: ClusterIP
  selector:
    app: identity
  ports:
    - port: 80
      targetPort: 5002
