# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CICD

on:
  push:
    branches: [ "main" ]

jobs:
  generate-version:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    - name: Github Tag Bump
      id: tag_bump
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INITIAL_VERSION: 1.0.1
        # 1.0.1, the first one "1" is the major, the second "0" is the minor, and the last one "1" is the patch
        # DEFAULT_BUMP is whenever we make changes, it will increse one more number and the number we want to 
        # increse is path, so we put it in "DEFAULT_BUMP"
        DEFAULT_BUMP: patch

    outputs:
      # steps.tag_bump.outputs.new_tag is the outputs from tag_bump and it has the new_tag as documented in 
      # anothrNick/github-tag-action@1.67.0 that we use above (please check document)
      new_version: ${{ steps.tag_bump.outputs.new_tag }}
  
  package-and-publish-contracts:

    runs-on: ubuntu-latest
    needs: generate-version

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Pack
      run: | 
        dotnet pack src/Play.Identity.Contracts/ \
        --configuration Release \
        -p:PackageVersion=${{ needs.generate-version.outputs.new_version }} \
        -p:RepositoryUrl=https://github.com/{{github.repository_owner}}/Play.Identity \
        -o packages
