# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CICD

on:
  push:
    branches: [ "main" ]

jobs:
  generate-version:
    runs-on: ubuntu-latest

    # this permissions uses for bumping the version
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    - name: Github Tag Bump
      id: tag_bump
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INITIAL_VERSION: 1.0.1
        # 1.0.1, the first one "1" is the major, the second "0" is the minor, and the last one "1" is the patch
        # DEFAULT_BUMP is whenever we make changes, it will increse one more number and the number we want to 
        # increse is path, so we put it in "DEFAULT_BUMP"
        DEFAULT_BUMP: patch

    outputs:
      # steps.tag_bump.outputs.new_tag is the outputs from tag_bump and it has the new_tag as documented in 
      # anothrNick/github-tag-action@1.67.0 that we use above (please check document)
      new_version: ${{ steps.tag_bump.outputs.new_tag }}
  
  package-and-publish-contracts:

    runs-on: ubuntu-latest
    needs: generate-version

    # this permission uses for publish to github package
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        source-url: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json
      env:
        # this "NUGET_AUTH_TOKEN" environment variable that the Nuget client already understands and he knows
        # that if it finds a token over there, it will use it to authenticate with whatever sources it has to
        # use.
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Pack
      run: | 
        dotnet pack src/Play.Identity.Contracts/ \
        --configuration Release \
        -p:PackageVersion=${{ needs.generate-version.outputs.new_version }} \
        -p:RepositoryUrl=https://github.com/${{github.repository_owner}}/Play.Identity \
        -o packages
    - name: Publish
      run: dotnet nuget push packages/*.nupkg

  build-and-deploy-service:
    runs-on: ubuntu-latest
    needs: generate-version

    env:
      ACR_NAME: samphamplayeconomyacr

    # The way we're going to enable authentication from Github into Azure is by following the OpenId Connect framework
    # which is now supported by Github. And as part of this framework, what needs to be created is an Id token. That's
    # going to have all the permissions necessary for the Github actions to interact with Azure.
    permissions:
      # this id-token: write allows for the actual creation and writing into the ID token that's going to be generated.
      # So you need to specify here or nothing else is going to work.
      id-token: write
      # this allows is for the access token to be able to actually read and clone contents of our GitHub repository.
      contents: read
    
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          # Client-id is the id we just created service principal. Navigating to Microsoft Entra ID (Azure Active Directory),
          # --> App Registrations --> at the "GitHub" row, copy the value at the column "Application (client) ID" and paste here
          # But this value should store in secrets.
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          # the tenant-id is it refers directly to the ID of the active directory organization that has been created for your Azure
          # account. Navigating to Microsoft Entra ID (Azure Active Directory), Tenant ID will be displayed here.
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          # subscription-id: navigating to your subscription and selecting subscritionId
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
          
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5.0.0
        with:
          # for GH_PAT, we cannot use secrets.GITHUB_TOKEN, because we will use Play.Common, and it belongs to
          # another repository, not in this repository
          secrets: | 
            "GH_OWNER=${{github.repository_owner}}"
            "GH_PAT=${{secrets.GH_PAT}}"
          tags: ${{env.ACR_NAME}}.azurecr.io/play.identity:${{ needs.generate-version.outputs.new_version }}
